# Generated by Django 4.0 on 2021-12-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past_questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='faculty',
        ),
        migrations.AddField(
            model_name='university',
            name='faculty',
            field=models.ManyToManyField(to='past_questions.Faculty'),
        ),
    ]
