# Generated by Django 4.0 on 2021-12-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past_questions', '0003_alter_department_level_alter_faculty_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='department',
        ),
        migrations.AddField(
            model_name='faculty',
            name='department',
            field=models.ManyToManyField(to='past_questions.Department'),
        ),
    ]
