# Generated by Django 4.0 on 2021-12-18 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('past_questions', '0008_remove_department_level_level_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='past_questions.level'),
        ),
    ]
