# Generated by Django 4.0 on 2021-12-18 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('past_questions', '0009_year_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='level',
        ),
        migrations.AddField(
            model_name='level',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='past_questions.year'),
        ),
    ]
