# Generated by Django 4.0 on 2021-12-18 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("past_questions", "0011_remove_semester_courses_course_semester"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="semester",
        ),
        migrations.AddField(
            model_name="level",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="past_questions.course",
            ),
        ),
    ]
