# Generated by Django 4.0 on 2021-12-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past_questions', '0014_rename_level_course_level_remove_level_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
