# Generated by Django 4.0 on 2021-12-21 00:59

from django.db import migrations, models
import past_questions.models


class Migration(migrations.Migration):

    dependencies = [
        ("past_questions", "0017_alter_past_question_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="past_question",
            name="file",
            field=models.FileField(upload_to=past_questions.models.pq_file_upload_path),
        ),
    ]
