# Generated by Django 4.0 on 2021-12-21 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("past_questions", "0018_alter_past_question_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="department",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="past_questions.department",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="past_questions.level",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="semester",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="past_questions.semester",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="year",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="past_questions.year",
            ),
        ),
    ]
