# Generated by Django 4.0 on 2021-12-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("past_questions", "0021_alter_university_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
