# Generated by Django 4.0 on 2021-12-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past_questions', '0024_alter_department_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
