# Generated by Django 4.0 on 2022-02-21 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("past_questions", "0035_university_website"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="university",
            name="faculty",
        ),
    ]
