# Generated by Django 4.0 on 2022-02-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("past_questions", "0036_remove_university_faculty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
