# Generated by Django 4.0 on 2022-03-03 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_is_volunteer"),
        ("past_questions", "0037_alter_faculty_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.customuser",
            ),
        ),
        migrations.AddField(
            model_name="pastquestion",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.customuser",
            ),
        ),
        migrations.AlterField(
            model_name="level",
            name="level",
            field=models.PositiveIntegerField(
                choices=[
                    (100, "100"),
                    (200, "200"),
                    (300, "300"),
                    (400, "400"),
                    (500, "500"),
                ],
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="year",
            name="year",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
