# Generated by Django 4.0 on 2022-03-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("past_questions", "0040_course_has_pastquestion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="university",
            name="name",
            field=models.CharField(max_length=250),
        ),
    ]
